In [19]:
# Import dependencies
import pandas as pd
import numpy as np
from pathlib import Path

In [20]:
# Read the data into a Pandas DataFrame
death_rate_data = Path('Resources/death_rate_of_countries_and_its_causes.csv')
death_rate_causes_df =  pd.read_csv(death_rates_data, encoding='ISO-8859-1')
death_rate_causes_df.head()

,Entity,Code,Year,Outdoor air pollution,High systolic blood pressure,Diet high in sodium,Diet low in whole grains,Alochol use,Diet low in fruits,Unsafe water source,...,High body mass index,Unsafe sanitation,No access to handwashing facility,Drug use,Low bone mineral density,Vitamin A deficiency,Child stunting,Discontinued breastfeeding,Non-exclusive breastfeeding,Iron deficiency
0,Afghanistan,AFG,1990,3169,25633,1045,7077,356,3185,3702,...,9518,2798,4825,174,389,2016,7686,107,2216,564
1,Afghanistan,AFG,1991,3222,25872,1055,7149,364,3248,4309,...,9489,3254,5127,188,389,2056,7886,121,2501,611
2,Afghanistan,AFG,1992,3395,26309,1075,7297,376,3351,5356,...,9528,4042,5889,211,393,2100,8568,150,3053,700
3,Afghanistan,AFG,1993,3623,26961,1103,7499,389,3480,7152,...,9611,5392,7007,232,411,2316,9875,204,3726,773
4,Afghanistan,AFG,1994,3788,27658,1134,7698,399,3610,7192,...,9675,5418,7421,247,413,2665,11031,204,3833,812

In [21]:
# get brief summary

death_rate_causes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6840 entries, 0 to 6839
Data columns (total 31 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Entity                                    6840 non-null   object
 1   Code                                      6150 non-null   object
 2   Year                                      6840 non-null   int64
 3   Outdoor air pollution                     6840 non-null   int64
 4   High systolic blood pressure              6840 non-null   int64
 5   Diet high in sodium                       6840 non-null   int64
 6   Diet low in whole grains                  6840 non-null   int64
 7   Alochol use                               6840 non-null   int64
 8   Diet low in fruits                        6840 non-null   int64
 9   Unsafe water source                       6840 non-null   int64
 10  Secondhand smoke                          6840 non-null   int64
 11  Low birth weight                          6840 non-null   int64
 12  Child wasting                             6840 non-null   int64
 13  Unsafe sex                                6840 non-null   int64
 14  Diet low in nuts and seeds                6840 non-null   int64
 15  Household air pollution from solid fuels  6840 non-null   int64
 16  Diet low in Vegetables                    6840 non-null   int64
 17  Low physical activity                     6840 non-null   int64
 18  Smoking                                   6840 non-null   int64
 19  High fasting plasma glucose               6840 non-null   int64
 20  Air pollution                             6840 non-null   int64
 21  High body mass index                      6840 non-null   int64
 22  Unsafe sanitation                         6840 non-null   int64
 23  No access to handwashing facility         6840 non-null   int64
 24  Drug use                                  6840 non-null   int64
 25  Low bone mineral density                  6840 non-null   int64
 26  Vitamin A deficiency                      6840 non-null   int64
 27  Child stunting                            6840 non-null   int64
 28  Discontinued breastfeeding                6840 non-null   int64
 29  Non-exclusive breastfeeding               6840 non-null   int64
 30  Iron deficiency                           6840 non-null   int64
dtypes: int64(29), object(2)
memory usage: 1.6+ MB

In [23]:
#
death_rate_causes_df['Air_Pollution'] = death_rate_causes_df['Outdoor air pollution'] + death_rate_causes_df['Air pollution']
death_rate_causes_df

,Entity,Code,Year,Outdoor air pollution,High systolic blood pressure,Diet high in sodium,Diet low in whole grains,Alochol use,Diet low in fruits,Unsafe water source,...,Unsafe sanitation,No access to handwashing facility,Drug use,Low bone mineral density,Vitamin A deficiency,Child stunting,Discontinued breastfeeding,Non-exclusive breastfeeding,Iron deficiency,Air_Pollution
0,Afghanistan,AFG,1990,3169,25633,1045,7077,356,3185,3702,...,2798,4825,174,389,2016,7686,107,2216,564,40400
1,Afghanistan,AFG,1991,3222,25872,1055,7149,364,3248,4309,...,3254,5127,188,389,2056,7886,121,2501,611,41537
2,Afghanistan,AFG,1992,3395,26309,1075,7297,376,3351,5356,...,4042,5889,211,393,2100,8568,150,3053,700,44567
3,Afghanistan,AFG,1993,3623,26961,1103,7499,389,3480,7152,...,5392,7007,232,411,2316,9875,204,3726,773,48111
4,Afghanistan,AFG,1994,3788,27658,1134,7698,399,3610,7192,...,5418,7421,247,413,2665,11031,204,3833,812,50422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6835,Zimbabwe,ZWE,2015,2835,11483,1063,1354,4854,1820,4336,...,2879,4328,1068,407,138,730,21,734,282,16081
6836,Zimbabwe,ZWE,2016,2781,11663,1082,1383,4915,1854,4244,...,2798,4295,1042,415,101,674,20,700,275,15912
6837,Zimbabwe,ZWE,2017,2700,11819,1098,1409,4992,1883,4193,...,2744,4251,1007,424,82,629,19,678,267,15626
6838,Zimbabwe,ZWE,2018,2669,12002,1117,1439,5044,1917,4013,...,2608,4153,969,434,85,607,17,644,261,15414
6839,Zimbabwe,ZWE,2019,2680,12241,1140,1475,5156,1960,3914,...,2531,4113,963,438,81,585,16,631,259,15347

In [27]:
column_names = death_rate_causes_df.columns
column_names

Index(['Entity', 'Code', 'Year', 'Outdoor air pollution',
       'High systolic blood pressure', 'Diet high in sodium ',
       'Diet low in whole grains', 'Alochol use', 'Diet low in fruits',
       'Unsafe water source', 'Secondhand smoke', 'Low birth weight',
       'Child wasting', 'Unsafe sex', 'Diet low in nuts and seeds',
       'Household air pollution from solid fuels', 'Diet low in Vegetables',
       'Low physical activity', 'Smoking', 'High fasting plasma glucose',
       'Air pollution', 'High body mass index', 'Unsafe sanitation',
       'No access to handwashing facility', 'Drug use',
       'Low bone mineral density', 'Vitamin A deficiency', 'Child stunting',
       'Discontinued breastfeeding', 'Non-exclusive breastfeeding',
       'Iron deficiency', 'Air_Pollution', 'Poor_Nutrition'],
      dtype='object')

In [31]:
death_rate_causes_df['Poor_Nutrition'] = death_rate_causes_df['Diet low in nuts and seeds'] + death_rate_causes_df['Diet low in whole grains']
+ death_rate_causes_df['Diet low in fruits'] + death_rate_causes_df['Diet low in Vegetables'] + death_rate_causes_df['Diet high in sodium ']
death_rate_causes_df

,Entity,Code,Year,Outdoor air pollution,High systolic blood pressure,Diet high in sodium,Diet low in whole grains,Alochol use,Diet low in fruits,Unsafe water source,...,No access to handwashing facility,Drug use,Low bone mineral density,Vitamin A deficiency,Child stunting,Discontinued breastfeeding,Non-exclusive breastfeeding,Iron deficiency,Air_Pollution,Poor_Nutrition
0,Afghanistan,AFG,1990,3169,25633,1045,7077,356,3185,3702,...,4825,174,389,2016,7686,107,2216,564,40400,9396
1,Afghanistan,AFG,1991,3222,25872,1055,7149,364,3248,4309,...,5127,188,389,2056,7886,121,2501,611,41537,9598
2,Afghanistan,AFG,1992,3395,26309,1075,7297,376,3351,5356,...,5889,211,393,2100,8568,150,3053,700,44567,9900
3,Afghanistan,AFG,1993,3623,26961,1103,7499,389,3480,7152,...,7007,232,411,2316,9875,204,3726,773,48111,10270
4,Afghanistan,AFG,1994,3788,27658,1134,7698,399,3610,7192,...,7421,247,413,2665,11031,204,3833,812,50422,10630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6835,Zimbabwe,ZWE,2015,2835,11483,1063,1354,4854,1820,4336,...,4328,1068,407,138,730,21,734,282,16081,1582
6836,Zimbabwe,ZWE,2016,2781,11663,1082,1383,4915,1854,4244,...,4295,1042,415,101,674,20,700,275,15912,1619
6837,Zimbabwe,ZWE,2017,2700,11819,1098,1409,4992,1883,4193,...,4251,1007,424,82,629,19,678,267,15626,1651
6838,Zimbabwe,ZWE,2018,2669,12002,1117,1439,5044,1917,4013,...,4153,969,434,85,607,17,644,261,15414,1688
6839,Zimbabwe,ZWE,2019,2680,12241,1140,1475,5156,1960,3914,...,4113,963,438,81,585,16,631,259,15347,1731

In [33]:
#dropping redundant columns
death_rate_causes_df = death_rate_causes_df.drop(columns=['Outdoor air pollution','Diet high in sodium ','Diet low in whole grains',
                                                         'Diet low in fruits','Diet low in Vegetables','Diet low in nuts and seeds','Air pollution'])
death_rate_causes_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6840 entries, 0 to 6839
Data columns (total 26 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Entity                                    6840 non-null   object
 1   Code                                      6150 non-null   object
 2   Year                                      6840 non-null   int64
 3   High systolic blood pressure              6840 non-null   int64
 4   Alochol use                               6840 non-null   int64
 5   Unsafe water source                       6840 non-null   int64
 6   Secondhand smoke                          6840 non-null   int64
 7   Low birth weight                          6840 non-null   int64
 8   Child wasting                             6840 non-null   int64
 9   Unsafe sex                                6840 non-null   int64
 10  Household air pollution from solid fuels  6840 non-null   int64
 11  Low physical activity                     6840 non-null   int64
 12  Smoking                                   6840 non-null   int64
 13  High fasting plasma glucose               6840 non-null   int64
 14  High body mass index                      6840 non-null   int64
 15  Unsafe sanitation                         6840 non-null   int64
 16  No access to handwashing facility         6840 non-null   int64
 17  Drug use                                  6840 non-null   int64
 18  Low bone mineral density                  6840 non-null   int64
 19  Vitamin A deficiency                      6840 non-null   int64
 20  Child stunting                            6840 non-null   int64
 21  Discontinued breastfeeding                6840 non-null   int64
 22  Non-exclusive breastfeeding               6840 non-null   int64
 23  Iron deficiency                           6840 non-null   int64
 24  Air_Pollution                             6840 non-null   int64
 25  Poor_Nutrition                            6840 non-null   int64
dtypes: int64(24), object(2)
memory usage: 1.4+ MB